# Module: beat
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/main/metricbeat-module-beat.html

- module: beat
  xpack.enabled: true
  period: 10s
  hosts: 
    - filebeat.${APP_HOST}:${MONITOR_PORT}
    - metricbeat.${APP_HOST}:${MONITOR_PORT}
  username: "beats_system"
  password: "${ELASTICSEARCH_PASSWORD}"
