# Module: tomcat
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/8.4/metricbeat-module-tomcat.html

- module: tomcat
  metricsets: ['threading', 'cache', 'memory', 'requests']
  period: 10s
  hosts: ['https://tombola.${APP_NICK}.tomcat.local:8443']
  protocol: "https"
  path: "/jolokia/?ignoreErrors=true&canonicalNaming=false"
  username: "jolokia"
  password: "jolokia"
  ssl:
    enabled: true
    certificate_authorities: ["${ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES}"]

